roles:
- name: HeaderSelected
  components: [Link]
  display_in_toolbox: false
- name: HeaderDefault
  components: [Link]
- name: HeaderHover
  components: [Link]
- name: AboutTxt
  components: [RichText]
  display_in_toolbox: false
- name: Submit
  components: [Button]
- name: FlowPanelSticky
  components: [FlowPanel]
- name: LandingImg
  components: [Image]
- name: ButtonPortfolio
  components: [Button]
